### ISSUE TITLE
Exec format error on raspberry pi 4

### ISSUE THREAD

**Issue by TheChiefMeat** [Magicalex/docker-mumble#1]
I've been trying to get this image to run on a new Raspberry pi 4, however I get the following from the docker logs:

```
pi@raspberrypi:~/docker-mumble $ sudo docker logs mumble
su-exec: /opt/mumble/murmur.x86: Exec format error
```

I've tried both running the image and building the image using the dockerfile.

**Comment by al3xLvs** [comment]
Indeed this image can't work with arm arch.
We need to compile murmur...

EDIT: I'm working on this https://wiki.mumble.info/wiki/BuildingLinux#Compiling_Mumble_and_Murmur

**Comment by al3xLvs** [comment]
@TheChiefMeat can you try again? I committed some change https://github.com/Magicalex/docker-mumble/commit/5a577b00d31a55b42f41a78c52ca1c08cbb83af2
